"""empty message

Revision ID: 133a13d14d33
Revises: cbd043af5fab
Create Date: 2020-04-10 16:11:58.273497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133a13d14d33'
down_revision = 'cbd043af5fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_challenges',
    sa.Column('from_student_id', sa.Integer(), nullable=False),
    sa.Column('to_student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['to_student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('from_student_id', 'to_student_id', 'quiz_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_challenges')
    # ### end Alembic commands ###
