"""empty message

Revision ID: 2774041408f2
Revises: bca7bbb41ef2
Create Date: 2020-03-12 07:59:36.515523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2774041408f2'
down_revision = 'bca7bbb41ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_quiz_course_assigns',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('course_index', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_index'], ['courses.index'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'course_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_quiz_course_assigns')
    # ### end Alembic commands ###
