"""empty message

Revision ID: 35f83d20e147
Revises: 31930450b94b
Create Date: 2020-03-12 07:41:52.785926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f83d20e147'
down_revision = '31930450b94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionattempts', sa.Column('student_id', sa.Integer(), nullable=False))
    op.drop_constraint('questionattempts_user_id_fkey', 'questionattempts', type_='foreignkey')
    op.create_foreign_key(None, 'questionattempts', 'students', ['student_id'], ['id'])
    op.drop_column('questionattempts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionattempts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questionattempts', type_='foreignkey')
    op.create_foreign_key('questionattempts_user_id_fkey', 'questionattempts', 'users', ['user_id'], ['id'])
    op.drop_column('questionattempts', 'student_id')
    # ### end Alembic commands ###
