"""empty message

Revision ID: 526b4809fdcf
Revises: 27c4344e9ef3
Create Date: 2020-04-12 10:09:22.174123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526b4809fdcf'
down_revision = '27c4344e9ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('winner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'winner_id')
    # ### end Alembic commands ###
