"""empty message

Revision ID: a09d09245f41
Revises: 63179c9dc054
Create Date: 2020-04-10 18:23:00.870295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09d09245f41'
down_revision = '63179c9dc054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'challenges', ['from_student_id', 'to_student_id', 'quiz_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challenges', type_='unique')
    # ### end Alembic commands ###
