"""empty message

Revision ID: bca7bbb41ef2
Revises: bcf6cab8bb21
Create Date: 2020-03-12 07:56:41.942532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bca7bbb41ef2'
down_revision = 'bcf6cab8bb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_student_course_enrols',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_index', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_index'], ['courses.index'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_index')
    )
    op.drop_table('Rs_student_course_enrols')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Rs_student_course_enrols',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_index', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_index'], ['courses.index'], name='Rs_student_course_enrols_course_index_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='Rs_student_course_enrols_student_id_fkey'),
    sa.PrimaryKeyConstraint('student_id', 'course_index', name='Rs_student_course_enrols_pkey')
    )
    op.drop_table('rs_student_course_enrols')
    # ### end Alembic commands ###
