"""empty message

Revision ID: bcff206399d2
Revises: 1064001a11ea
Create Date: 2020-03-12 07:49:38.188831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcff206399d2'
down_revision = '1064001a11ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_staff_course_teaches',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('course_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_index'], ['courses.index'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'course_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_staff_course_teaches')
    # ### end Alembic commands ###
