"""empty message

Revision ID: cea6467636b0
Revises: 7026ad4a1511
Create Date: 2020-03-12 05:26:40.143766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea6467636b0'
down_revision = '7026ad4a1511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffs', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('students', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'created_at')
    op.drop_column('staffs', 'created_at')
    # ### end Alembic commands ###
