"""empty message

Revision ID: e60585833910
Revises: 133a13d14d33
Create Date: 2020-04-10 16:28:38.302746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e60585833910'
down_revision = '133a13d14d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_student_id', sa.Integer(), nullable=False),
    sa.Column('to_student_id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['to_student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id', 'from_student_id', 'to_student_id', 'quiz_id')
    )
    op.drop_table('rs_challenges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_challenges',
    sa.Column('from_student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_student_id'], ['students.id'], name='rs_challenges_from_student_id_fkey'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='rs_challenges_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['to_student_id'], ['students.id'], name='rs_challenges_to_student_id_fkey'),
    sa.PrimaryKeyConstraint('from_student_id', 'to_student_id', 'quiz_id', name='rs_challenges_pkey')
    )
    op.drop_table('Challenges')
    # ### end Alembic commands ###
