"""empty message

Revision ID: efa0491a74f4
Revises: bcff206399d2
Create Date: 2020-03-12 07:50:48.566190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efa0491a74f4'
down_revision = 'bcff206399d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rs_staff_course_teaches',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('course_index', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_index'], ['courses.index'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'course_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rs_staff_course_teaches')
    # ### end Alembic commands ###
